 package display.base.font;

 import java.awt.Point;

 public final class Special {

 	public static Point PT_PLUS[] = { new Point(4,3),
																		new Point(2,1),
																		new Point(2,2),
																		new Point(2,3),
																		new Point(2,4),
																		new Point(2,5),
																		new Point(0,3),
																		new Point(1,3),
																		new Point(3,3) };

  public static Point PT_PROMPT[] = { new Point(4,6),
																		     new Point(3,6),
                                         new Point(2,6),
                                         new Point(1,6),
                                         new Point(0,6) };

  //vierspur
  public static Point PT_VIERSPUR[] = { new Point(52,0),
                                        new Point(51,0),
                                        new Point(50,0),
                                        new Point(49,0),
                                        new Point(48,0),
                                        new Point(47,0),
                                        new Point(46,0),
                                        new Point(45,0),
                                        new Point(44,0),
                                        new Point(43,0),
                                        new Point(42,0),
                                        new Point(41,0),
                                        new Point(40,0),
                                        new Point(39,0),
                                        new Point(38,0),
                                        new Point(37,0),
                                        new Point(36,0),
                                        new Point(35,0),
                                        new Point(34,0),
                                        new Point(33,0),
                                        new Point(32,0),
                                        new Point(31,0),
                                        new Point(30,0),
                                        new Point(29,0),
                                        new Point(28,0),
                                        new Point(27,0),
                                        new Point(26,0),
                                        new Point(25,0),
                                        new Point(24,0),
                                        new Point(23,0),
                                        new Point(22,0),
                                        new Point(21,0),
                                        new Point(20,0),
                                        new Point(19,0),
                                        new Point(18,0),
                                        new Point(17,0),
                                        new Point(16,0),

                                        new Point(52,1),
                                        new Point(51,1),
                                        new Point(15,1),

                                        new Point(52,2),
                                        new Point(50,2),
                                        new Point(47,2),
                                        new Point(46,2),
                                        new Point(45,2),
                                        new Point(44,2),
                                        new Point(43,2),
                                        new Point(42,2),
                                        new Point(41,2),
                                        new Point(40,2),
                                        new Point(39,2),
                                        new Point(38,2),
                                        new Point(37,2),
                                        new Point(36,2),
                                        new Point(33,2),
                                        new Point(28,2),
                                        new Point(23,2),
                                        new Point(18,2),
                                        new Point(14,2),

                                        new Point(52,3),
                                        new Point(49,3),
                                        new Point(46,3),
                                        new Point(35,3),
                                        new Point(13,3),

                                        new Point(52,4),
                                        new Point(48,4),
                                        new Point(45,4),
                                        new Point(42,4),
                                        new Point(37,4),
                                        new Point(34,4),
                                        new Point(31,4),
                                        new Point(26,4),
                                        new Point(21,4),
                                        new Point(16,4),
                                        new Point(12,4),

                                        new Point(52,5),
                                        new Point(47,5),
                                        new Point(44,5),
                                        new Point(33,5),
                                        new Point(11,5),

                                        new Point(52,6),
                                        new Point(46,6),
                                        new Point(43,6),
                                        new Point(32,6),
                                        new Point(29,6),
                                        new Point(24,6),
                                        new Point(19,6),
                                        new Point(14,6),
                                        new Point(10,6),

                                        new Point(52,7),
                                        new Point(45,7),
                                        new Point(42,7),
                                        new Point(41,7),
                                        new Point(40,7),
                                        new Point(39,7),
                                        new Point(38,7),
                                        new Point(37,7),
                                        new Point(36,7),
                                        new Point(35,7),
                                        new Point(34,7),
                                        new Point(33,7),
                                        new Point(32,7),
                                        new Point(31,7),
                                        new Point(9,7),

                                        new Point(52,8),
                                        new Point(44,8),
                                        new Point(27,8),
                                        new Point(22,8),
                                        new Point(17,8),
                                        new Point(12,8),
                                        new Point(8,8),

                                        new Point(52,9),
                                        new Point(51,9),
                                        new Point(43,9),
                                        new Point(39,9),
                                        new Point(38,9),
                                        new Point(37,9),
                                        new Point(35,9),
                                        new Point(34,9),
                                        new Point(33,9),
                                        new Point(31,9),
                                        new Point(30,9),
                                        new Point(29,9),
                                        new Point(26,9),
                                        new Point(21,9),
                                        new Point(16,9),
                                        new Point(11,9),
                                        new Point(7,9),

                                        new Point(50,10),
                                        new Point(42,10),
                                        new Point(25,10),
                                        new Point(20,10),
                                        new Point(15,10),
                                        new Point(10,10),
                                        new Point(6,10),

                                        new Point(49,11),
                                        new Point(48,11),
                                        new Point(41,11),
                                        new Point(24,11),
                                        new Point(19,11),
                                        new Point(14,11),
                                        new Point(9,11),
                                        new Point(5,11),

                                        new Point(47,12),
                                        new Point(40,12),
                                        new Point(23,12),
                                        new Point(18,12),
                                        new Point(13,12),
                                        new Point(8,12),
                                        new Point(4,12),

                                        new Point(46,13),
                                        new Point(45,13),
                                        new Point(39,13),
                                        new Point(35,13),
                                        new Point(34,13),
                                        new Point(31,13),
                                        new Point(30,13),
                                        new Point(27,13),
                                        new Point(26,13),
                                        new Point(22,13),
                                        new Point(17,13),
                                        new Point(12,13),
                                        new Point(7,13),
                                        new Point(3,13),

                                        new Point(44,14),
                                        new Point(38,14),
                                        new Point(34,14),
                                        new Point(33,14),
                                        new Point(30,14),
                                        new Point(29,14),
                                        new Point(26,14),
                                        new Point(25,14),
                                        new Point(21,14),
                                        new Point(16,14),
                                        new Point(11,14),
                                        new Point(6,14),
                                        new Point(2,14),

                                        new Point(43,15),
                                        new Point(42,15),
                                        new Point(37,15),
                                        new Point(1,15),

                                        new Point(41,16),
                                        new Point(36,16),
                                        new Point(35,16),
                                        new Point(34,16),
                                        new Point(33,16),
                                        new Point(32,16),
                                        new Point(31,16),
                                        new Point(30,16),
                                        new Point(29,16),
                                        new Point(28,16),
                                        new Point(27,16),
                                        new Point(26,16),
                                        new Point(25,16),
                                        new Point(24,16),
                                        new Point(23,16),
                                        new Point(22,16),
                                        new Point(21,16),
                                        new Point(20,16),
                                        new Point(19,16),
                                        new Point(18,16),
                                        new Point(17,16),
                                        new Point(16,16),
                                        new Point(15,16),
                                        new Point(14,16),
                                        new Point(13,16),
                                        new Point(12,16),
                                        new Point(11,16),
                                        new Point(10,16),
                                        new Point(9,16),
                                        new Point(8,16),
                                        new Point(7,16),
                                        new Point(6,16),
                                        new Point(5,16),
                                        new Point(4,16),
                                        new Point(3,16),
                                        new Point(2,16),
                                        new Point(1,16),
                                        new Point(0,16),

                                        new Point(40,17),
                                        new Point(39,17),
                                        new Point(36,17),
                                        new Point(0,17),

                                        new Point(38,18),
                                        new Point(36,18),
                                        new Point(23,18),
                                        new Point(17,18),
                                        new Point(0,18),

                                        new Point(37,19),
                                        new Point(36,19),
                                        new Point(35,19),
                                        new Point(34,19),
                                        new Point(33,19),
                                        new Point(32,19),
                                        new Point(31,19),
                                        new Point(30,19),
                                        new Point(29,19),
                                        new Point(28,19),
                                        new Point(27,19),
                                        new Point(26,19),
                                        new Point(25,19),
                                        new Point(24,19),
                                        new Point(23,19),
                                        new Point(22,19),
                                        new Point(21,19),
                                        new Point(20,19),
                                        new Point(19,19),
                                        new Point(18,19),
                                        new Point(17,19),
                                        new Point(16,19),
                                        new Point(15,19),
                                        new Point(14,19),
                                        new Point(13,19),
                                        new Point(12,19),
                                        new Point(11,19),
                                        new Point(10,19),
                                        new Point(9,19),
                                        new Point(8,19),
                                        new Point(7,19),
                                        new Point(6,19),
                                        new Point(5,19),
                                        new Point(4,19),
                                        new Point(3,19),
                                        new Point(2,19),
                                        new Point(1,19),
                                        new Point(0,19) };

	//Brandenburger Tor
	public static Point PT_BT[] = { new Point(13,10),
																	new Point(6,0),
																	new Point(7,0),
																	new Point(5,1),
																	new Point(6,1),
																	new Point(7,1),
																	new Point(8,1),
																	new Point(0,2),
																	new Point(0,3),
																	new Point(0,10),
																	new Point(2,2),
																	new Point(2,3),
																	new Point(2,10),
																	new Point(4,2),
																	new Point(4,3),
																	new Point(4,10),
																	new Point(6,2),
																	new Point(6,3),
																	new Point(6,10),
																	new Point(7,2),
																	new Point(7,3),
																	new Point(7,10),
																	new Point(9,2),
																	new Point(9,3),
																	new Point(9,10),
																	new Point(11,2),
																	new Point(11,3),
																	new Point(11,10),
																	new Point(13,2),
																	new Point(13,3),
																	new Point(1,2),
																	new Point(1,3),
																	new Point(1,4),
																	new Point(1,5),
																	new Point(1,6),
																	new Point(1,7),
																	new Point(1,8),
																	new Point(1,9),
																	new Point(1,10),
																	new Point(3,2),
																	new Point(3,3),
																	new Point(3,4),
																	new Point(3,5),
																	new Point(3,6),
																	new Point(3,7),
																	new Point(3,8),
																	new Point(3,9),
																	new Point(3,10),
																	new Point(5,2),
																	new Point(5,3),
																	new Point(5,4),
																	new Point(5,5),
																	new Point(5,6),
																	new Point(5,7),
																	new Point(5,8),
																	new Point(5,9),
																	new Point(5,10),
																	new Point(8,2),
																	new Point(8,3),
																	new Point(8,4),
																	new Point(8,5),
																	new Point(8,6),
																	new Point(8,7),
																	new Point(8,8),
																	new Point(8,9),
																	new Point(8,10),
																	new Point(10,2),
																	new Point(10,3),
																	new Point(10,4),
																	new Point(10,5),
																	new Point(10,6),
																	new Point(10,7),
																	new Point(10,8),
																	new Point(10,9),
																	new Point(10,10),
																	new Point(12,2),
																	new Point(12,3),
																	new Point(12,4),
																	new Point(12,5),
																	new Point(12,6),
																	new Point(12,7),
																	new Point(12,8),
																	new Point(12,9),
																	new Point(12,10) };

  //Pfeil
  public static Point PT_PFEIL[] = { new Point(0,0),

                                     new Point(0,1),
                                     new Point(1,1),

                                     new Point(0,2),
                                     new Point(1,2),
                                     new Point(2,2),

                                     new Point(0,3),
                                     new Point(1,3),
                                     new Point(2,3),
                                     new Point(3,3),

                                     new Point(0,4),
                                     new Point(1,4),
                                     new Point(2,4),
                                     new Point(3,4),
                                     new Point(4,4),

                                     new Point(0,5),
                                     new Point(1,5),
                                     new Point(2,5),
                                     new Point(3,5),
                                     new Point(4,5),
                                     new Point(5,5),

                                     new Point(0,6),
                                     new Point(1,6),
                                     new Point(2,6),
                                     new Point(3,6),
                                     new Point(4,6),
                                     new Point(5,6),
                                     new Point(6,6),

                                     new Point(0,7),
                                     new Point(1,7),
                                     new Point(2,7),
                                     new Point(3,7),
                                     new Point(4,7),
                                     new Point(5,7),
                                     new Point(6,7),
                                     new Point(7,7),

                                     new Point(0,8),
                                     new Point(1,8),
                                     new Point(2,8),
                                     new Point(3,8),
                                     new Point(4,8),
                                     new Point(0,9),
                                     new Point(1,9),
                                     new Point(3,9),
                                     new Point(4,9),
                                     new Point(0,10),
                                     new Point(4,10),
                                     new Point(5,10),
                                     new Point(4,11),
                                     new Point(5,11),
                                     new Point(5,12),
                                     new Point(6,12),
                                     new Point(5,13),
                                     new Point(6,13) };

 }