 package display.base.font;

 import java.awt.Point;

 public final class Standart {

 	//Zahlen
	public static Point PT_0[] = { new Point( 4,5 ),
																 new Point( 0,1 ),
																 new Point( 0,2 ),
																 new Point( 0,3 ),
																 new Point( 0,4 ),
																 new Point( 0,5 ),
																 new Point( 1,1 ),
																 new Point( 1,2 ),
																 new Point( 1,3 ),
																 new Point( 1,4 ),
																 new Point( 1,5 ),
																 new Point( 1,0 ),
																 new Point( 2,0 ),
																 new Point( 3,0 ),
																 new Point( 4,1 ),
																 new Point( 4,2 ),
																 new Point( 4,3 ),
																 new Point( 4,4 ),
																 new Point( 3,1 ),
																 new Point( 3,2 ),
																 new Point( 3,3 ),
																 new Point( 3,4 ),
																 new Point( 3,5 ),
																 new Point( 1,6 ),
																 new Point( 2,6 ),
																 new Point( 3,6 ) };

	public static Point PT_2[] = { new Point( 4,1 ),
																 new Point( 0,1 ),
																 new Point( 1,0 ),
																 new Point( 1,1 ),
																 new Point( 2,0 ),
																 new Point( 3,0 ),
																 new Point( 3,2 ),
																 new Point( 2,3 ),
																 new Point( 2,4 ),
																 new Point( 1,4 ),
																 new Point( 0,5 ),
																 new Point( 0,6 ),
																 new Point( 1,5 ),
																 new Point( 1,6 ),
																 new Point( 2,6 ),
																 new Point( 3,1 ),
																 new Point( 3,3 ),
																 new Point( 3,6 ),
																 new Point( 4,2 ),
																 new Point( 4,6 ) };

	public static Point PT_9[] = { new Point( 4,1 ),
																 new Point( 0,1 ),
																 new Point( 0,2 ),
																 new Point( 1,0 ),
																 new Point( 2,0 ),
																 new Point( 3,0 ),
																 new Point( 4,2 ),
																 new Point( 4,3 ),
																 new Point( 4,4 ),
																 new Point( 3,5 ),
																 new Point( 3,4 ),
																 new Point( 2,5 ),
																 new Point( 2,6 ),
																 new Point( 1,3 ),
																 new Point( 2,3 ),
																 new Point( 3,3 ),
																 new Point( 1,1 ),
																 new Point( 1,2 ),
																 new Point( 3,1 ),
																 new Point( 3,2 ),
																 new Point( 1,6 ) };


	//Buchstaben
  public static Point PT_BLANK[] = {};

	public static Point PT_A[] = { new Point( 4,3 ),
																 new Point( 1,2 ),
																 new Point( 2,2 ),
																 new Point( 3,2 ),
																 new Point( 1,5 ),
																 new Point( 1,4 ),
																 new Point( 2,4 ),
																 new Point( 0,5 ),
																 new Point( 1,6 ),
																 new Point( 2,6 ),
																 new Point( 3,3 ),
																 new Point( 4,4 ),
																 new Point( 4,5 ),
																 new Point( 4,6 ),
																 new Point( 3,4 ),
																 new Point( 3,5 ),
																 new Point( 3,6 ) };

	public static Point PT_B[] = { new Point( 4,4 ),
																 new Point( 0,0 ),
																 new Point( 0,1 ),
																 new Point( 0,2 ),
																 new Point( 0,3 ),
																 new Point( 0,4 ),
																 new Point( 0,5 ),
																 new Point( 0,6 ),
																 new Point( 1,0 ),
																 new Point( 1,1 ),
																 new Point( 1,2 ),
																 new Point( 1,3 ),
																 new Point( 1,4 ),
																 new Point( 1,5 ),
																 new Point( 1,6 ),
																 new Point( 2,2 ),
																 new Point( 3,2 ),
																 new Point( 3,3 ),
																 new Point( 3,4 ),
																 new Point( 3,5 ),
																 new Point( 4,3 ),
																 new Point( 4,5 ),
																 new Point( 2,6 ),
																 new Point( 3,6 ) };

	public static Point PT_C[] = { new Point( 4,2 ),
																 new Point( 1,2 ),
																 new Point( 2,2 ),
																 new Point( 3,2 ),
																 new Point( 0,3 ),
																 new Point( 1,3 ),
																 new Point( 1,5 ),
																 new Point( 0,4 ),
																 new Point( 1,4 ),
																 new Point( 0,5 ),
																 new Point( 1,6 ),
																 new Point( 2,6 ),
																 new Point( 3,6 ),
																 new Point( 4,6 ) };

	public static Point PT_D[] = { new Point( 4,4 ),
																 new Point( 3,6 ),
																 new Point( 3,0 ),
																 new Point( 3,1 ),
																 new Point( 3,2 ),
																 new Point( 3,3 ),
																 new Point( 3,4 ),
																 new Point( 3,5 ),
																 new Point( 3,6 ),
																 new Point( 4,0 ),
																 new Point( 4,1 ),
																 new Point( 4,2 ),
																 new Point( 4,3 ),
																 new Point( 4,5 ),
																 new Point( 4,6 ),
																 new Point( 1,2 ),
																 new Point( 1,3 ),
																 new Point( 1,4 ),
																 new Point( 1,5 ),
																 new Point( 1,6 ),
																 new Point( 2,2 ),
																 new Point( 2,6 ),
																 new Point( 0,3 ),
																 new Point( 0,4 ),
																 new Point( 0,5 ) };

	public static Point PT_E[] = { new Point( 4,3 ),
																 new Point( 1,2 ),
																 new Point( 2,2 ),
																 new Point( 3,2 ),
																 new Point( 0,3 ),
																 new Point( 1,3 ),
																 new Point( 1,5 ),
																 new Point( 3,3 ),
																 new Point( 3,4 ),
																 new Point( 4,4 ),
																 new Point( 0,4 ),
																 new Point( 1,4 ),
																 new Point( 2,4 ),
																 new Point( 3,4 ),
																 new Point( 0,5 ),
																 new Point( 1,6 ),
																 new Point( 2,6 ),
																 new Point( 3,6 ),
																 new Point( 4,6 ) };

  public static Point PT_F[] = { new Point( 4,0 ),
                                 new Point( 3,0 ),
                                 new Point( 0,2 ),
                                 new Point( 3,2 ),
																 new Point( 1,1 ),
																 new Point( 1,2 ),
																 new Point( 1,3 ),
																 new Point( 1,4 ),
																 new Point( 1,5 ),
                                 new Point( 1,6 ),
																 new Point( 2,0 ),
																 new Point( 2,1 ),
																 new Point( 2,2 ),
																 new Point( 2,3 ),
																 new Point( 2,4 ),
																 new Point( 2,5 ),
																 new Point( 2,6 ),
																 new Point( 2,2 ) };


  public static Point PT_G[] = { new Point( 4,4 ),
																 new Point( 0,3 ),
																 new Point( 0,4 ),
																 new Point( 0,5 ),
																 new Point( 1,2 ),
																 new Point( 1,3 ),
																 new Point( 1,4 ),
																 new Point( 1,5 ),
																 new Point( 1,6 ),
																 new Point( 1,8 ),
																 new Point( 2,2 ),
																 new Point( 3,2 ),
																 new Point( 3,3 ),
																 new Point( 3,4 ),
																 new Point( 3,5 ),
																 new Point( 3,6 ),
																 new Point( 3,7 ),
																 new Point( 3,8 ),
																 new Point( 4,3 ),
																 new Point( 4,5 ),
																 new Point( 4,6 ),
																 new Point( 4,7 ),
																 new Point( 2,6 ),
																 new Point( 2,8 ),
																 new Point( 3,6 ) };

  public static Point PT_H[] = {  new Point( 4,6 ),
																	new Point( 0,0 ),
																	new Point( 0,1 ),
																	new Point( 1,0 ),
																	new Point( 1,1 ),
																	new Point( 0,6 ),
																	new Point( 0,5 ),
																	new Point( 0,4 ),
																	new Point( 0,3 ),
																	new Point( 0,2 ),
																	new Point( 1,6 ),
																	new Point( 1,5 ),
																	new Point( 1,4 ),
																	new Point( 1,3 ),
																	new Point( 1,2 ),
																	new Point( 2,2 ),
																	new Point( 3,6 ),
																	new Point( 3,5 ),
																	new Point( 3,4 ),
																	new Point( 3,3 ),
																	new Point( 3,2 ),
																	new Point( 4,5 ),
																	new Point( 4,4 ),
																	new Point( 4,3 )};

	public static Point PT_I[] = { new Point( 1,2 ),
																 new Point( 0,2 ),
																 new Point( 0,3 ),
																 new Point( 0,4 ),
																 new Point( 0,5 ),
																 new Point( 0,6 ),
																 new Point( 1,3 ),
																 new Point( 1,4 ),
																 new Point( 1,5 ),
																 new Point( 1,6 ),
																 new Point( 0,0 ),
																 new Point( 1,0 ) };

  public static Point PT_J[] = { new Point( 3,0 ),
                                 new Point( 2,0 ),
                                 new Point( 1,2 ),
                                 new Point( 2,2 ),
                                 new Point( 3,2 ),
                                 new Point( 2,3 ),
                                 new Point( 3,3 ),
                                 new Point( 2,4 ),
                                 new Point( 3,4 ),
                                 new Point( 2,4 ),
                                 new Point( 3,4 ),
                                 new Point( 2,5 ),
                                 new Point( 3,5 ),
                                 new Point( 2,6 ),
                                 new Point( 3,6 ),
                                 new Point( 0,7 ),
                                 new Point( 2,7 ),
                                 new Point( 1,8 ),
                                 new Point( 2,8 ),
                                 new Point( 3,7 ) };

	public static Point PT_K[] = { new Point( 4,6 ),
																 new Point( 4,2 ),
																 new Point( 3,3 ),
																 new Point( 3,5 ),
																 new Point( 2,4 ),
																 new Point( 0,0 ),
																 new Point( 0,1 ),
																 new Point( 0,2 ),
																 new Point( 0,3 ),
																 new Point( 0,4 ),
																 new Point( 0,5 ),
																 new Point( 0,6 ),
																 new Point( 1,0 ),
																 new Point( 1,1 ),
																 new Point( 1,2 ),
																 new Point( 1,3 ),
																 new Point( 1,4 ),
																 new Point( 1,5 ),
																 new Point( 1,6 ) };

	public static Point PT_L[] = { new Point( 1,1 ),
																 new Point( 0,0 ),
																 new Point( 0,1 ),
																 new Point( 0,2 ),
																 new Point( 0,3 ),
																 new Point( 0,4 ),
																 new Point( 0,5 ),
																 new Point( 0,6 ),
																 new Point( 1,0 ),
																 new Point( 1,2 ),
																 new Point( 1,3 ),
																 new Point( 1,4 ),
																 new Point( 1,5 ),
																 new Point( 1,6 ) };

	public static Point PT_M[] = {  new Point( 7,3 ),
																	new Point( 0,6 ),
																	new Point( 0,5 ),
																	new Point( 0,4 ),
																	new Point( 0,3 ),
																	new Point( 0,2 ),
																	new Point( 1,6 ),
																	new Point( 1,5 ),
																	new Point( 1,4 ),
																	new Point( 1,3 ),
																	new Point( 1,2 ),
																	new Point( 2,2 ),
																	new Point( 3,6 ),
																	new Point( 3,5 ),
																	new Point( 3,4 ),
																	new Point( 3,3 ),
																	new Point( 3,2 ),
																	new Point( 4,5 ),
																	new Point( 4,4 ),
																	new Point( 4,3 ),
																	new Point( 4,2 ),
																	new Point( 5,2 ),
																	new Point( 6,2 ),
																	new Point( 6,3 ),
																	new Point( 6,4 ),
																	new Point( 6,5 ),
																	new Point( 6,6 ),
																	new Point( 4,6 ),
																	new Point( 7,4 ),
																	new Point( 7,5 ),
																	new Point( 7,6 ) };

	public static Point PT_N[] = {  new Point( 4,6 ),
																	new Point( 0,6 ),
																	new Point( 0,5 ),
																	new Point( 0,4 ),
																	new Point( 0,3 ),
																	new Point( 0,2 ),
																	new Point( 1,6 ),
																	new Point( 1,5 ),
																	new Point( 1,4 ),
																	new Point( 1,3 ),
																	new Point( 1,2 ),
																	new Point( 2,2 ),
																	new Point( 3,6 ),
																	new Point( 3,5 ),
																	new Point( 3,4 ),
																	new Point( 3,3 ),
																	new Point( 3,2 ),
																	new Point( 4,5 ),
																	new Point( 4,4 ),
																	new Point( 4,3 )};

	public static Point PT_O[] = { new Point(4,3),
																 new Point(4,4),
																 new Point(4,5),
																 new Point(3,3),
																 new Point(3,4),
																 new Point(3,5),
																 new Point(2,2),
																 new Point(2,6),
																 new Point(3,2),
																 new Point(3,6),
																 new Point(1,2),
																 new Point(1,3),
																 new Point(1,4),
																 new Point(1,5),
																 new Point(1,6),
																 new Point(0,3),
																 new Point(0,4),
																 new Point(0,5) };

	public static Point PT_P[] = { new Point( 4,3 ),
																 new Point( 0,2 ),
																 new Point( 0,3 ),
																 new Point( 0,4 ),
																 new Point( 0,5 ),
																 new Point( 0,6 ),
																 new Point( 0,7 ),
																 new Point( 0,8 ),
																 new Point( 1,2 ),
																 new Point( 1,3 ),
																 new Point( 1,4 ),
																 new Point( 1,5 ),
																 new Point( 1,6 ),
																 new Point( 1,7 ),
																 new Point( 1,8 ),
																 new Point( 2,2 ),
																 new Point( 3,2 ),
																 new Point( 3,3 ),
																 new Point( 3,4 ),
																 new Point( 3,5 ),
																 new Point( 4,5 ),
																 new Point( 4,4 ),
																 new Point( 2,6 ),
																 new Point( 3,6 ) };

  public static Point PT_Q[] = { new Point(4,3),
																 new Point(4,4),
																 new Point(4,5),
																 new Point(3,3),
																 new Point(3,4),
																 new Point(3,5),
																 new Point(2,2),
																 new Point(2,6),
																 new Point(3,2),
																 new Point(3,6),
																 new Point(1,2),
																 new Point(1,3),
																 new Point(1,4),
																 new Point(1,5),
																 new Point(1,6),
																 new Point(0,3),
																 new Point(0,4),
                                 new Point(4,6),
                                 new Point(3,7),
																 new Point(4,7),
																 new Point(3,8),
																 new Point(4,8),
																 new Point(0,5) };

	public static Point PT_R[] = { new Point( 3,3 ),
																 new Point( 3,2 ),
																 new Point( 2,3 ),
																 new Point( 0,2 ),
																 new Point( 0,3 ),
																 new Point( 0,4 ),
																 new Point( 0,5 ),
																 new Point( 0,6 ),
																 new Point( 1,2 ),
																 new Point( 1,4 ),
																 new Point( 1,5 ),
																 new Point( 1,6 ),
																 new Point( 1,3 ) };

	public static Point PT_S[] = { new Point( 3,4 ),
																 new Point( 1,2 ),
																 new Point( 2,2 ),
																 new Point( 3,2 ),
																 new Point( 0,3 ),
																 new Point( 0,4 ),
																 new Point( 1,3 ),
																 new Point( 1,4 ),
																 new Point( 2,4 ),
																 new Point( 2,5 ),
																 new Point( 3,5 ),
																 new Point( 0,6 ),
																 new Point( 1,6 ),
																 new Point( 2,6 ) };

	public static Point PT_T[] = { new Point( 3,6 ),
																 new Point( 0,0 ),
																 new Point( 0,1 ),
																 new Point( 0,2 ),
																 new Point( 0,3 ),
																 new Point( 0,4 ),
																 new Point( 0,5 ),
																 new Point( 1,0 ),
																 new Point( 1,1 ),
																 new Point( 1,2 ),
																 new Point( 1,3 ),
																 new Point( 1,4 ),
																 new Point( 1,5 ),
																 new Point( 1,6 ),
																 new Point( 2,2 ),
																 new Point( 2,6 ) };

	public static Point PT_U[] = {  new Point( 4,3 ),
																	new Point( 0,2 ),
																	new Point( 0,3 ),
																	new Point( 0,4 ),
																	new Point( 0,5 ),
																	new Point( 4,2 ),
																	new Point( 1,2 ),
																	new Point( 1,3 ),
																	new Point( 1,4 ),
																	new Point( 1,5 ),
																	new Point( 1,6 ),
																	new Point( 1,3 ),
																	new Point( 3,3 ),
																	new Point( 2,6 ),
																	new Point( 3,2 ),
																	new Point( 4,4 ),
																	new Point( 4,5 ),
																	new Point( 4,6 ),
																	new Point( 3,4 ),
																	new Point( 3,5 ),
																	new Point( 3,6 ) };

	public static Point PT_V[] = { new Point( 4,3 ),
																 new Point( 0,2 ),
																 new Point( 0,3 ),
																 new Point( 1,2 ),
																 new Point( 1,3 ),
																 new Point( 3,2 ),
																 new Point( 3,3 ),
																 new Point( 3,3 ),
																 new Point( 4,2 ),
																 new Point( 1,4 ),
																 new Point( 1,5 ),
																 new Point( 2,4 ),
																 new Point( 2,5 ),
																 new Point( 3,4 ),
																 new Point( 2,6 ),
																 new Point( 3,5 ) };

	public static Point PT_W[] = { new Point( 7,2 ),
																 new Point( 4,3 ),
																 new Point( 0,2 ),
																 new Point( 0,3 ),
																 new Point( 1,2 ),
																 new Point( 1,3 ),
																 new Point( 3,2 ),
																 new Point( 3,3 ),
																 new Point( 7,3 ),
																 new Point( 3,3 ),
																 new Point( 4,2 ),
																 new Point( 4,4 ),
																 new Point( 4,5 ),
																 new Point( 1,4 ),
																 new Point( 1,5 ),
																 new Point( 2,4 ),
																 new Point( 2,5 ),
																 new Point( 3,4 ),
																 new Point( 5,4 ),
																 new Point( 5,5 ),
																 new Point( 5,6 ),
																 new Point( 5,4 ),
																 new Point( 6,5 ),
																 new Point( 6,2 ),
																 new Point( 6,3 ),
																 new Point( 6,4 ),
																 new Point( 2,6 ),
																 new Point( 3,5 ) };

	public static Point PT_X[] = { new Point( 4,6 ),
																 new Point( 0,2 ),
																 new Point( 1,3 ),
																 new Point( 1,2 ),
																 new Point( 3,2 ),
																 new Point( 1,6 ),
																 new Point( 3,6 ),
																 new Point( 2,3 ),
																 new Point( 2,5 ),
																 new Point( 2,4 ),
																 new Point( 3,3 ),
																 new Point( 4,2 ),
																 new Point( 1,5 ),
																 new Point( 0,6 ),
																 new Point( 3,5 ) };

  public static Point PT_Y[] = { new Point( 4,2 ),
                                 new Point( 3,2 ),
                                 new Point( 1,2 ),
                                 new Point( 0,2 ),
                                 new Point( 4,3 ),
                                 new Point( 3,3 ),
                                 new Point( 1,3 ),
                                 new Point( 0,3 ),
                                 new Point( 4,4 ),
                                 new Point( 3,4 ),
                                 new Point( 1,4 ),
                                 new Point( 0,4 ),
                                 new Point( 1,5 ),
                                 new Point( 2,5 ),
                                 new Point( 3,5 ),
                                 new Point( 2,6 ),
                                 new Point( 3,6 ),
                                 new Point( 2,7 ),
                                 new Point( 3,7 ),
                                 new Point( 1,8 ),
                                 new Point( 2,8 ) };

  public static Point PT_Z[] = { new Point( 4,2 ),
                                 new Point( 3,2 ),
                                 new Point( 2,2 ),
                                 new Point( 1,2 ),
                                 new Point( 0,2 ),
                                 new Point( 2,3 ),
                                 new Point( 3,3 ),
                                 new Point( 1,4 ),
                                 new Point( 2,4 ),
                                 new Point( 0,5 ),
                                 new Point( 1,5 ),
                                 new Point( 4,6 ),
                                 new Point( 3,6 ),
                                 new Point( 2,6 ),
                                 new Point( 1,6 ),
                                 new Point( 0,6 ) };
 }
